-- MRO Agent — server-side chat history
-- Apply with: mysql -h 39.107.14.53 -P 3307 -u root -p d_mymro_sample < 002_create_chat_history.sql

CREATE TABLE IF NOT EXISTS t_chat_session (
    id VARCHAR(64) NOT NULL PRIMARY KEY,            -- session id generated by frontend
    user_id INT NOT NULL,                            -- FK to t_user.id (logical, not enforced)
    title VARCHAR(200) NOT NULL DEFAULT '新对话',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_updated (user_id, updated_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS t_chat_message (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    role VARCHAR(16) NOT NULL,                       -- 'user' | 'assistant'
    content MEDIUMTEXT,                              -- message text
    image_data MEDIUMTEXT,                           -- base64-encoded image (user messages only)
    sku_results JSON,                                -- assistant SKU results
    competitor_results JSON,                         -- assistant competitor results
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_session_id (session_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
